---
- name: "install Ansible dependencies"
  package:
    name:
      - python3
      - python3-pip
      - libselinux-python
      - libsemanage-python
    state: present
  become: true
  when: ansible_pkg_mgr != 'homebrew' and ZOOKEEPER_PYTHON == '/usr/bin/python'
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
- name: "install podman dependency"
  package:
    name:
      - podman
    state: present
  become: true
  when: ZOOKEEPER_USE_PODMAN and ansible_pkg_mgr != 'homebrew' and ZOOKEEPER_PYTHON == '/usr/bin/python3'
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
- name: Set container_manage_cgroup flag on to run podman containers as systemd services and keep it persistent across reboots
  ansible.posix.seboolean:
    name: container_manage_cgroup
    state: true
    persistent: true
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: Check for the {{ ZOOKEEPER_NAME }} download
  stat:
    path: "{{ ZOOKEEPER_DOWNLOAD_DEST }}"
  register: ZOOKEEPER_DOWNLOAD
- name: Check if javac command exists
  stat:
    path: /usr/bin/javac
  register: JAVAC_EXISTS
- name: Install {{ ZOOKEEPER_NAME }} dependencies. 
  package:
    name: [java-1.8.0-openjdk]
    state: present
  become: yes
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Install {{ ZOOKEEPER_NAME }} dependencies. 
  package:
    name: [openjdk,gnu-tar]
    state: present
  when: ansible_pkg_mgr == 'homebrew'
- name: Link openjdk to Library
  file:
    src: /usr/local/opt/openjdk/libexec/openjdk.jdk
    dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
    state: link
  become: true
  when: ansible_pkg_mgr == 'homebrew'
- name: Create the {{ ZOOKEEPER_NAME }} source directory {{ ZOOKEEPER_SRC }}. 
  file:
    name: "{{ ZOOKEEPER_SRC }}"
    state: directory
    owner: "{{ USER_NAME }}"
  become: yes
- name: Download the {{ ZOOKEEPER_NAME }} application. 
  get_url:
    url: "{{ ZOOKEEPER_DOWNLOAD_URL }}"
    dest: "{{ ZOOKEEPER_DOWNLOAD_DEST }}"
  when: not ZOOKEEPER_DOWNLOAD.stat.exists
- name: Create the {{ ZOOKEEPER_NAME }} install directory {{ ZOOKEEPER_OPT }}. 
  file:
    name: "{{ ZOOKEEPER_OPT }}"
    state: directory
    owner: "{{ ZOOKEEPER_USER }}"
  become: true
- name: Install {{ ZOOKEEPER_NAME }} into the {{ ZOOKEEPER_OPT }} install directory. 
  unarchive:
    src: "{{ ZOOKEEPER_DOWNLOAD_DEST }}"
    dest: "{{ ZOOKEEPER_OPT }}"
    remote_src: true
    extra_opts: [--strip-components=1]
  become: true
- name: Create the {{ ZOOKEEPER_NAME }} conf directory {{ ZOOKEEPER_CONF }}
  file:
    name: "{{ ZOOKEEPER_CONF }}"
    state: directory
    owner: "{{ ZOOKEEPER_USER }}"
    mode: 0777
  become: true
- name: Create the {{ ZOOKEEPER_NAME }} config file {{ ZOOKEEPER_CONF }}/zoo.cfg
  template:
    src: zookeeper_config.j2
    dest: "{{ ZOOKEEPER_CONF }}/zoo.cfg"
  become: true
- name: Create the {{ ZOOKEEPER_NAME }} log4j.properties file {{ ZOOKEEPER_CONF }}/log4j.properties
  template:
    src: zookeeper_log4j.properties
    dest: "{{ ZOOKEEPER_CONF }}/log4j.properties"
  become: true
- name: set SELinux permissions on {{ ZOOKEEPER_CONF }}
  sefcontext:
    target: "{{ ZOOKEEPER_CONF }}"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: set SELinux permissions on {{ ZOOKEEPER_CONF }}/*
  sefcontext:
    target: "{{ ZOOKEEPER_CONF }}/*"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: reload SELinux policy to ensure that {{ ZOOKEEPER_NAME }} is executable
  command: "restorecon -irv {{ ZOOKEEPER_CONF }}"
  become: true
  when: ZOOKEEPER_USE_PODMAN
- name: Create the {{ ZOOKEEPER_NAME }} data directory {{ ZOOKEEPER_DATA }}
  file:
    name: "{{ ZOOKEEPER_DATA }}"
    state: directory
    owner: "{{ ZOOKEEPER_USER }}"
    mode: 0777
  become: true
- name: set SELinux permissions on {{ ZOOKEEPER_DATA }}
  sefcontext:
    target: "{{ ZOOKEEPER_DATA }}"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: reload SELinux policy to ensure that {{ ZOOKEEPER_NAME }} is executable
  command: "restorecon -irv {{ ZOOKEEPER_DATA }}"
  become: true
  when: ZOOKEEPER_USE_PODMAN
- name: Create the {{ ZOOKEEPER_NAME }} systemd service {{ ZOOKEEPER_SYSTEMD }}
  template:
    src: zookeeper_systemd_service.j2
    dest: "{{ ZOOKEEPER_SYSTEMD }}"
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Reload the services
  systemd:
    daemon_reload: true
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Start and enable the {{ ZOOKEEPER_NAME }} service
  service:
    name: "{{ ZOOKEEPER_SERVICE }}"
    enabled: true
    state: restarted
  become: true
  when: ansible_pkg_mgr != 'homebrew'

- name: Create the {{ ZOOKEEPER_NAME }} launchd service.
  template:
    src: zookeeper_launchd_service.j2
    dest: "~/Library/LaunchAgents/org.zookeeper.plist"
  when: ansible_pkg_mgr == 'homebrew'
- name: Load the {{ ZOOKEEPER_NAME }} launchd service.
  shell: launchctl load ~/Library/LaunchAgents/org.zookeeper.plist
  when: ansible_pkg_mgr == 'homebrew'
- name: Start the {{ ZOOKEEPER_NAME }} launchd service.
  shell: launchctl start org.zookeeper
  when: ansible_pkg_mgr == 'homebrew'
