---
- name: "Install dependencies as root: {{ ZOOKEEPER_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ ZOOKEEPER_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
- name: "Install dependencies as user {{ ZOOKEEPER_USER }}: {{ ZOOKEEPER_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ ZOOKEEPER_DEPENDENCIES }}"
  when: INSTALL_DEPENDENCIES.failed
- name: Check for the {{ ZOOKEEPER_NAME }} download
  stat:
    path: "{{ ZOOKEEPER_DOWNLOAD_DEST }}"
  register: ZOOKEEPER_DOWNLOAD
- name: Check if javac command exists
  stat:
    path: /usr/bin/javac
  register: JAVAC_EXISTS
- name: Install {{ ZOOKEEPER_NAME }} dependencies. 
  package:
    name: [openjdk,gnu-tar]
    state: present
  when: ansible_pkg_mgr == 'homebrew'
  ignore_errors: true
- name: Link openjdk to Library
  file:
    src: /usr/local/opt/openjdk/libexec/openjdk.jdk
    dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
    state: link
  become: true
  when: ansible_pkg_mgr == 'homebrew'
- name: Create the {{ ZOOKEEPER_NAME }} source directory {{ ZOOKEEPER_SRC }}. 
  file:
    name: "{{ ZOOKEEPER_SRC }}"
    state: directory
- name: Download the {{ ZOOKEEPER_NAME }} application. 
  get_url:
    url: "{{ ZOOKEEPER_DOWNLOAD_URL }}"
    dest: "{{ ZOOKEEPER_DOWNLOAD_DEST }}"
  when: not ZOOKEEPER_DOWNLOAD.stat.exists
- name: Create the {{ ZOOKEEPER_NAME }} install directory {{ ZOOKEEPER_OPT }}. 
  file:
    name: "{{ ZOOKEEPER_OPT }}"
    state: directory
- name: Install {{ ZOOKEEPER_NAME }} into the {{ ZOOKEEPER_OPT }} install directory. 
  unarchive:
    src: "{{ ZOOKEEPER_DOWNLOAD_DEST }}"
    dest: "{{ ZOOKEEPER_OPT }}"
    remote_src: true
    extra_opts: [--strip-components=1]
- name: Create the {{ ZOOKEEPER_NAME }} conf directory {{ ZOOKEEPER_CONF }}
  file:
    name: "{{ ZOOKEEPER_CONF }}"
    state: directory
    mode: 0777
- name: Create the {{ ZOOKEEPER_NAME }} config file {{ ZOOKEEPER_CONF }}/zoo.cfg
  template:
    src: zookeeper_config.j2
    dest: "{{ ZOOKEEPER_CONF }}/zoo.cfg"
- name: Create the {{ ZOOKEEPER_NAME }} log4j.properties file {{ ZOOKEEPER_CONF }}/log4j.properties
  template:
    src: zookeeper_log4j.properties
    dest: "{{ ZOOKEEPER_CONF }}/log4j.properties"
- name: set SELinux permissions on {{ ZOOKEEPER_CONF }}
  sefcontext:
    target: "{{ ZOOKEEPER_CONF }}"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: set SELinux permissions on {{ ZOOKEEPER_CONF }}/*
  sefcontext:
    target: "{{ ZOOKEEPER_CONF }}/*"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: reload SELinux policy to ensure that {{ ZOOKEEPER_NAME }} is executable
  command: "restorecon -irv {{ ZOOKEEPER_CONF }}"
  become: true
  when: ZOOKEEPER_USE_PODMAN
- name: Create the {{ ZOOKEEPER_NAME }} data directory {{ ZOOKEEPER_DATA }}
  file:
    name: "{{ ZOOKEEPER_DATA }}"
    state: directory
    mode: 0777
- name: set SELinux permissions on {{ ZOOKEEPER_DATA }}
  sefcontext:
    target: "{{ ZOOKEEPER_DATA }}"
    setype: container_file_t
  become: true
  vars:
    ansible_python_interpreter: "{{ ZOOKEEPER_PYTHON }}"
  when: ZOOKEEPER_USE_PODMAN
- name: reload SELinux policy to ensure that {{ ZOOKEEPER_NAME }} is executable
  command: "restorecon -irv {{ ZOOKEEPER_DATA }}"
  become: true
  when: ZOOKEEPER_USE_PODMAN
- name: Create the {{ ZOOKEEPER_NAME }} systemd service {{ ZOOKEEPER_SYSTEMD }}
  template:
    src: zookeeper_systemd_service.j2
    dest: "{{ ZOOKEEPER_SYSTEMD }}"
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Reload the services
  systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 else 'user' }}"
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Start and enable the {{ ZOOKEEPER_NAME }} service
  service:
    name: "{{ ZOOKEEPER_SERVICE }}"
    enabled: true
    state: restarted
    scope: "{{ 'system' if ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 else 'user' }}"
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
  when: ansible_pkg_mgr != 'homebrew'

- name: Create the {{ ZOOKEEPER_NAME }} launchd service.
  template:
    src: zookeeper_launchd_service.j2
    dest: "~/Library/LaunchAgents/org.zookeeper.plist"
  when: ansible_pkg_mgr == 'homebrew'
- name: Load the {{ ZOOKEEPER_NAME }} launchd service.
  shell: launchctl load ~/Library/LaunchAgents/org.zookeeper.plist
  when: ansible_pkg_mgr == 'homebrew'
- name: Start the {{ ZOOKEEPER_NAME }} launchd service.
  shell: launchctl start org.zookeeper
  when: ansible_pkg_mgr == 'homebrew'
